### PR TITLE
Changed advertised listener of kafka

### PR DESCRIPTION
**Pull request by ashishmalgawa**
When we create a kafka adapter in streampipes, it fails with the following message in the schema generation step. 
`System error while guess the schema of the data ; 
Connect Worker: http://connect-worker-main:8098/api/v1/admin@streampipes.de/worker/guess/schema is currently not available. Sorry, something went wrong! Hit the feedback button (top right corner) to ask for help. If you think you’ve found a bug, fill an issue on our Github Page`

Also, in the logs of docker image of connect-main, the following message was coming
`10:26:26.415 SP [Thread-6] WARN  o.apache.kafka.clients.NetworkClient - [Consumer clientId=b1810568-12ba-43d5-a6ed-770828f823f2, groupId=ea8a814c-56b1-4fa0-8539-c313ab60453a] Connection to node 1001 (localhost/127.0.0.1:9094) could not be established. Broker may not be available`

After this fix, all the errors were resolved.

### CODE REVIEW

**Comment by wipatrick** [comment]
Hi @ashishmalgawa thanks for the PR! This is a weird behaviour since we rely on this `OUTSIDE` kafka listener interface for development purposes, e.g. for pipeline element development when we run Kafka and StreamPipes backend inside Docker and develop in the IDE (e.g. IntelliJ).

May I ask how you created the kafka adapter in StreamPipes connect? What are your settings, e.g. kafka broker host and port

**Comment by ashishmalgawa** [comment]
I used "kafka" as broker hostname, and port "9094" , and the topic that I selected was org.apache.streampipes.examples.flowrate-1

**Comment by wipatrick** [comment]
I see. can you try the following:

broker hostname: kafka
port: 9092

Other than that, we currently deploy data sources simulating event stream such as the flowrate sensor 1 & 2 that are are part of the `lite` version. If you use the CLI you see the entry `sources-watertank-simulator` [templates/lite](https://github.com/apache/incubator-streampipes-installer/blob/master/cli/templates/lite) that linkes to the corresponding docker-compose file in [services/sources-watertank-simulator/docker-compose.yml](https://github.com/apache/incubator-streampipes-installer/blob/master/cli/services/sources-watertank-simulator/docker-compose.yml).

This is a simulated data stream that is already available as a data stream (source) within the pipeline editor and ready to be used. So there is no need in connecting it again to via StreamPipes connect.

**Comment by wipatrick** [comment]
@ashishmalgawa I close this PR as I don't see an issue with the kafka listeners. If this should still be relevant, we can reopen it.

**Pull request closed without merging**
